###
POST http://localhost:3000/groups
Content-Type: application/json

{
    "name":"N1124",
    "teacher_id":11,
    "direction_id":9
}

###
GET http://localhost:3000/groups?direction_id=9
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTEsInJvbGUiOiJ0ZWFjaGVyIiwiaWF0IjoxNjg3MjE3NTk4fQ._i13z3WWXAv63lRxPbqw53gtX7yHncY0ka5vNeqjqUE

###
GET  http://localhost:3000/groups/16
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6InRlYWNoZXIiLCJpYXQiOjE2ODcxNzc5NTd9.NFE7fM5z3zYMXD55LRgABjYloLGK3b8gMQGY4FEWueo

###
POST http://localhost:3000/groups/16/students/21
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTEsInJvbGUiOiJ0ZWFjaGVyIiwiaWF0IjoxNjg3MjE3NTk4fQ._i13z3WWXAv63lRxPbqw53gtX7yHncY0ka5vNeqjqUE

###
GET http://localhost:3000/groups_students
