###
POST http://localhost:3000/groups
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Mywicm9sZSI6ImFkbWluIiwiaWF0IjoxNjg3NDk4NDIzfQ.mskJyLtLJcezjV5nhYADilP99yXNmmeLUFdzPOut0GU
Content-Type: application/json

{
    "name":"N124",
    "teacher_id":2
}

###
GET http://localhost:3000/groups
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Mywicm9sZSI6ImFkbWluIiwiaWF0IjoxNjg3NDk4NDIzfQ.mskJyLtLJcezjV5nhYADilP99yXNmmeLUFdzPOut0GU


###
GET  http://localhost:3000/groups/2
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Mywicm9sZSI6ImFkbWluIiwiaWF0IjoxNjg3NDk4NDIzfQ.mskJyLtLJcezjV5nhYADilP99yXNmmeLUFdzPOut0GU

###
POST http://localhost:3000/groups/2/students/3
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Mywicm9sZSI6ImFkbWluIiwiaWF0IjoxNjg3NDk4NDIzfQ.mskJyLtLJcezjV5nhYADilP99yXNmmeLUFdzPOut0GU

###
GET http://localhost:3000/groups_students

###
POST  http://localhost:3000/groups_students
Content-Type: application/json

{
    "student_id": 11,
      "group_id": 1
}
