###
POST http://localhost:3000/groups
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6InRlYWNoZXIiLCJpYXQiOjE2ODcxNzc5NTd9.NFE7fM5z3zYMXD55LRgABjYloLGK3b8gMQGY4FEWueo
Content-Type: application/json

{
    "name":"N84",
    "teacher_id":1
}

###
GET http://localhost:3000/groups
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6InRlYWNoZXIiLCJpYXQiOjE2ODcxNzc5NTd9.NFE7fM5z3zYMXD55LRgABjYloLGK3b8gMQGY4FEWueo

###
GET  http://localhost:3000/groups/14
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6InRlYWNoZXIiLCJpYXQiOjE2ODcxNzc5NTd9.NFE7fM5z3zYMXD55LRgABjYloLGK3b8gMQGY4FEWueo

###
GET http://localhost:3000/groups_students
