### Add stuff
POST http://localhost:3000/stuff
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjgsInJvbGUiOiJ0ZWFjaGVyIiwiaWF0IjoxNjg2OTUxMzAzfQ.0cTZLyveZPkKpg6uIwaaSl3NcqjDlj6ckOjzhvz_zoU
Content-Type: application/json

{
  "first_name": "Alisher",
  "last_name": "Abdullayev",
  "role": "teacher",
  "username": "alisher11",
  "password": "12345"
}
####  Login schema
POST http://localhost:3000/login
Content-Type: application/json

{
 "username": "alisher111",
  "password": "12345"
}


### List stuff
GET http://localhost:3000/stuff
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6OCwicm9sZSI6InRlYWNoZXIiLCJpYXQiOjE2ODY5NTE5MzF9.rFZwtXqKPl8oLfbWnhSA9uEguDfPaKrduXPn0CMdXJ4
# query params: role, q

### Show single stuff
GET http://localhost:3000/stuff/5
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6OCwicm9sZSI6InRlYWNoZXIiLCJpYXQiOjE2ODY5NTE5MzF9.rFZwtXqKPl8oLfbWnhSA9uEguDfPaKrduXPn0CMdXJ4
### Update stuff
PATCH http://localhost:3000/stuff/5
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjgsInJvbGUiOiJ0ZWFjaGVyIiwiaWF0IjoxNjg2OTUxMzAzfQ.0cTZLyveZPkKpg6uIwaaSl3NcqjDlj6ckOjzhvz_zoU
Content-Type: application/json

{
  "first_name": "MuhammadSodiq",
  "last_name": "Mirziyoyev",
  "username": "mirziyoyev" 
}

### Delete stuff
DELETE http://localhost:3000/stuff/5
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6OCwicm9sZSI6InRlYWNoZXIiLCJpYXQiOjE2ODY5NTE5MzF9.rFZwtXqKPl8oLfbWnhSA9uEguDfPaKrduXPn0CMdXJ4
